#!/bin/bash
set -euo pipefail
# ===== Configuraciones iniciales =====
export LC_ALL=C
DEFAULT_DESKTOP=1
MINIMAL_INSTALL="n"  
USER_HOME="/home/${SUDO_USER:-$USER}"
USER_NAME="${SUDO_USER:-$USER}"

# ===== Paquetes opcionales (solo instalación completa) =====
echo "en extras"
echo "Instalacion minima: $MINIMAL_INSTALL"

if [[ "$MINIMAL_INSTALL" != "s" ]]; then
  echo "dentro del if"

    desktop_choices="escritorioxyz"

    IFS=',' read -ra choices <<< "${desktop_choices:-$DEFAULT_DESKTOP}"
    
    for choice in "${choices[@]}"; do
        case "$(tr -d '[:space:]' <<< "$choice")" in
            1) echo "opcion 1" ;;
            2) echo "opcion 2" ;;
            3) echo "opcion 3" ;;            4) pacman -S --noconfirm --overwrite '*' plasma kde-applications ;;
            *) echo "Opción $choice omitida" ;;
        esac
    done
fi
echo "fuera del if"

./refresh
