#!/usr/bin/env bash
set -euo pipefail
# Configurar colores
RED='\033[31m'
GREEN='\033[32m'
YELLOW='\033[33m'
NC='\033[0m'

hostname="temporalxyz"

# Verificar que el archivo sudoers existe antes de moverlo
if [ -e /sudoers ]; then
    mv /sudoers /etc/
else
    echo "Advertencia: /sudoers no existe. Se omitirá el movimiento."
fi

# Configuración de zona horaria
ln -sf /usr/share/zoneinfo/America/Tegucigalpa /etc/localtime

# Configuración de locales
echo "es_HN.UTF-8 UTF-8" >> /etc/locale.gen
echo "LANG=es_HN.UTF-8" > /etc/locale.conf
locale-gen

# Sincronizar el reloj de hardware
hwclock -w

# Solicitar al usuario el nombre de host
#read -rp "Ingrese el nombre de host deseado: " hostname
#if [ -z "$hostname" ]; then
#    echo "No se ingresó ningún nombre. Usando 'dse-pc' por defecto."
#    hostname="dse-pc"
#fi

echo "$hostname" > /etc/hostname

# Ejecutar configuración de usuarios
echo -e "\033[32m==== USUARIOS ====\033[0m"
./usuarios
