#!/usr/bin/bash

mv /sudoers /etc/
echo dse-pc > /etc/hostname
ln -sf /usr/share/zoneinfo/America/Tegucigalpa /etc/localtime
echo "es_HN.UTF-8 UTF-8" >> /etc/locale.gen
echo LANG=es_HN.UTF-8 > /etc/locale.conf
locale-gen
hwclock -w
./grub
