#!/usr/bin/bash


echo
echo
echo "Discos disponibles para trabajar"
echo "Seleccionar uno: /dev/sdX"
echo 
echo

fdisk -l | grep Dis | cut -d "," -f1
echo
# en unidad se debe escribir el nombre y direccion del disco "/dev/sdX
read unidad


echo
echo
echo "¿Crear SWAP? [S/N]"
read swap
echo 
echo

tamanio=$(fdisk -l | grep $unidad | grep bytes | cut -d ',' -f 3 | cut -d ' ' -f 2)

home=$((tamanio/2))
(

# arranque del bios
# particion 1 
echo o
echo n
echo p
echo
echo
echo +1M

# Formato Bios Boot
echo t
echo 4

# EFI
# particion 2
echo n
echo p
echo
echo
echo +100M

#home
# particion 3
echo n 		#nueva particion
echo p 		#tipo particion
echo		#nro de particion
echo		#primer sector
echo $home	#ultimo sector

if [ $swap = "S" ] || [ $swap = "s" ]
then
	echo n
	echo p
	echo
	echo
	echo +8G
	
	echo t
	echo 4
	echo 82
fi

#raiz
# particion 4
echo n
echo p
echo
echo 
echo

echo w
) | fdisk $unidad 

echo "======Formateando particiones ======"

if [ $swap = "S" ] || [ $swap = "s" ]
then
	mkswap "$unidad"4
	swapon "$unidad"4
	mkfs.ext4 "$unidad"5
else
	mkfs.ext4 "$unidad"4
fi

mkfs.fat -F32 "$unidad"2
mkfs.ext4 "$unidad"3

echo "=====Montando unidades======="

if [ $swap = "S" ] || [ $swap = "s" ]
then
	mount "$unidad"5 /mnt
	echo "/mnt montado"
else
	mount "$unidad"4 /mnt
	echo "/mnt montado"
fi
mkdir -p /mnt/home
mount "$unidad"3 /mnt/home
echo "home montado"
mkdir -p /mnt/boot/EFI
mount "$unidad"2 /mnt/boot/EFI
echo "EFI montado"
echo
echo

echo " Instalar paquetes "
./paquetes
