#!/usr/bin/bash

(
echo o
echo n
echo p
echo
echo
echo +100M
echo n
echo p
echo
echo
echo
echo w
) | fdisk /dev/sda

echo "======Formateando particiones IFI, / ======"

mkfs.vfat -F32 /dev/sda1
mkfs.ext4 /dev/sda2

echo "=====Montando unidades======="

mount /dev/sda2 /mnt
mkdir -p /mnt/boot/efi

mount /dev/sda1 /mnt/boot/efi

./paquetes
