#!/usr/bin/bash

echo "Recomiendo hacer el particionado de discos de forma manual"
echo "Para tener una referencia de que manera realizar dicho particionado"
echo "Puede leer el codigo del archivo 'discos'"
echo
echo 

echo
echo
echo "Discos disponibles para trabajar"
echo "Seleccionar uno: /dev/sdX"
echo 
echo

fdisk -l | grep Dis | grep /dev/sd | cut -d "," -f1 | cut -d " " -f2,3,4
#fdisk -l | grep Dis | cut -d "," -f1
echo
# en unidad se debe escribir el nombre y direccion del disco "/dev/sdX
read unidad

tamanio=$(fdisk -l | grep $unidad | grep bytes | cut -d ',' -f 3 | cut -d ' ' -f 2)

home=$((tamanio/2))

(
# arranque del bios
# particion 1 
echo o
echo n
echo p
echo
echo
echo +1M

# Formato Bios Boot
echo t
echo 4

# EFI
# particion 2
echo n
echo p
echo
echo
echo +100M

echo t
echo 2
echo ef

#home
# particion 3
echo n 		#nueva particion
echo p 		#tipo particion
echo		#nro de particion
echo		#primer sector
echo $home	#ultimo sector

#raiz
# particion 4 
echo n
echo p
echo
echo 
echo

echo w
) | fdisk $unidad 

echo "======Formateando particiones ======"

mkfs.ext4 "$unidad"4
mkfs.ext4 "$unidad"3
mkfs.fat -F32 "$unidad"2

echo "=====Montando unidades======="

echo "creando directorio home ..."
mkdir -p /mnt/home
echo "creando directorio EFI ..."
mkdir -p /mnt/boot/EFI

echo "/mnt montando ... "
mount "$unidad"4 /mnt
echo "montando home ..."
mount "$unidad"3 /mnt/home
echo "montando EFI ..."
mount "$unidad"2 /mnt/boot/EFI
echo
echo " Instalar paquetes "
./paquetes
