#!/usr/bin/bash

# Configuraciones tomadas de repos git

# Configurar i3wm
cd /opt
git clone https://github.com/solimanhub/i3wn.git
while IFS= read -r line
do
  u="$line"
done < user

rm /home/$u/.config/i3/config
mv i3wn/config /home/$u/.config/i3/
rm -rf i3wn

# Configurar Bashrc
git clone https://github.com/SolimanHub/bashrc.git
mv bashrc /home/$u/.config/
ln -s /home/$u/.config/bashrc/.bashrc /home/$u/.bashrc
ln -s /home/$u/.config/bashrc/.bashrc /root/.bashrc
source /home/$u/.config/bashrc/.bashrc


# Configurar AUR
git clone https://aur.archlinux.org/yay.git
cd yay/

while IFS= read -r line
do
  u="$line"
done < ../user

chmod 777 PKGBUILD
mv PKGBUILD /home/$u/
su $u
cd ~/
echo "===== Contrase;a de Root ====="
makepkg -si
exit
rm -r /opt/*
