#!/usr/bin/bash
set -e -u

# actualizando las bases para evitar errores
pacman -Syy
pacman -S grub --noconfirm

grub-install /dev/sda
grub-mkconfig -o /boot/grub/grub.cfg
rm /etc/default/grub
mv ./grub_conf /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

echo "===== Contraseña root ====="
passwd

echo "===== Crear usuario: ======"
echo "Nombre de Usuario:"
read usuario

#crea un archivo user, se usa en extras
echo $usuario > /opt/user

useradd -m -g users -G audio,lp,optical,storage,video,wheel,games,power,scanner -s /bin/bash $usuario && passwd $usuario

chmod +x extras
./extras
