#!/usr/bin/env bash
set -euo pipefail

loadkeys es

read -rp "¿Desea hacer el particionado manual? [S/N] " respuesta

if [[ "${respuesta,,}" =~ ^s?$ ]]; then
    echo -e "\nExcelente elección. Al finalizar ejecute el script: ./paquetes"
else
    ./discos_gdisk
fi
