#!/usr/bin/bash

pacstrap /mnt base base-devel efibootmgr networkmanager grub gvfs gvfs-afc gvfs-mtp xdg-user-dirs linux linux-firmware dhcpcd neovim netctl wpa_supplicant dialog xf86-input-synaptics

genfstab -pU /mnt >> /mnt/etc/fstab

./pre-conf
