#!/usr/bin/bash
set -e -u

cp ./configs/* /mnt
cp conf /mnt
cp grub /mnt
cp extras /mnt
cp usuarios /mnt
cp yay_install /mnt
cp -r Luv /mnt
cp -r fonts/ /mnt

echo "====== ./conf ====="

arch-chroot /mnt
