#!/usr/bin/bash
set -e -u

cp sudoers /mnt
cp user_conf /mnt
cp conf /mnt
cp grub /mnt
cp inss /mnt
cp extras /mnt
cp lightdm.conf /mnt
cp -r Paquetes /mnt
cp -r Luv /mnt

echo "====== ./conf ====="

arch-chroot /mnt
