#!/usr/bin/bash
set -i -u

yay -S pop-gtk-theme
cd ~
mkdir .config/i3
cd .config/i3
curl -O https://raw.githubusercontent.com/SolimanHub/i3wn/master/config
cd ../
git clone https://github.com/SolimanHub/xfce4.git
cd xfce4/

