#!/bin/bash
set -euo pipefail
user_home="/home/$(ls --ignore lost*)"

cd "$user_home"
sudo -u "$(ls /home/ --ignore lost*)" bash <<EOF
  git clone https://aur.archlinux.org/yay.git yay
  cd yay && makepkg -si --noconfirm
  rm -rf yay

  yay -S --noconfirm \
      nerd-fonts-fira-code \
      papirus-icon-theme \
      pop-gtk-theme \
      tela-icon-theme \
      zsh-theme-powerlevel10k
EOF

cd /
echo -e "\033[32m==== LIMPIAR ====\033[0m"
#./limpiar
